before_install:
  - pod repo update > /dev/null
script:
  - xcodebuild -destination 'platform=iOS Simulator,name=iPhone 7' -workspace Cosmic.xcworkspace -scheme Cosmic -enableCodeCoverage YES test
after_script:
  - bash <(curl -s https://codecov.io/bash)


language: objective-c
osx_image: xcode9.3
xcode_workspace: Cosmic.xcworkspace # path to your xcodeproj folder
xcode_scheme: Cosmic
