codecov:
  notify:
    require_ci_to_pass: yes
coverage:
  status:
    project:
      default:
        target: 80...90
  range: 80...90
  round: down
  precision: 1
  ignore:
    - Tests/
    - cosmicPlaygrounds/
    - Package.swift
